- name: "Add Node.js from Nodesource"
  become: true
  shell: |
      curl -sL https://deb.nodesource.com/setup_13.x 1 sudo -E bash 

- name: "Install node.js 13"
  become: true
  apt:
   name: ["nodejs"]
   state: latest
   update_cache: yes

- name: "instapp pm global"
  npm:
   name: pm2
   gloabal: yes